# Generated by Django 4.2.1 on 2025-01-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valeur_cadorim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('rechargements_especes', models.IntegerField(default=0, verbose_name='Rechargements en Espèces Mauri Pay')),
                ('chargement_transfert', models.IntegerField(default=0, verbose_name='Chargement Transfert Bancaire')),
                ('paiement_facture', models.IntegerField(default=0, verbose_name='Paiement de Facture Mauri Pay')),
                ('paiement_marchand', models.IntegerField(default=0, verbose_name='Paiement Marchand')),
                ('paiement_salaire', models.IntegerField(default=0, verbose_name='Paiement de Salaire Mauri Pay')),
                ('rechargements_telephoniques', models.IntegerField(default=0, verbose_name='Rechargements Téléphoniques Mauri Pay')),
                ('transactions_administrations', models.IntegerField(default=0, verbose_name='Transactions avec les Administrations Publiques')),
                ('transfert_p2p', models.IntegerField(default=0, verbose_name='Transfert Personne à Personne Mauri Pay')),
                ('transfert_p2e', models.IntegerField(default=0, verbose_name='Transfert Personne à Entreprise')),
                ('retraits_cashout_cadorim', models.IntegerField(default=0, verbose_name='Retraits (Cash-out) Cadorim SA')),
                ('retraits_cashout_mauripay', models.IntegerField(default=0, verbose_name='Retraits (Cash-out) Mauri Pay')),
            ],
        ),
        migrations.CreateModel(
            name='Volume_cadorim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('rechargements_especes', models.IntegerField(default=0, verbose_name='Rechargements en Espèces Mauri Pay')),
                ('chargement_transfert', models.IntegerField(default=0, verbose_name='Chargement Transfert Bancaire')),
                ('paiement_facture', models.IntegerField(default=0, verbose_name='Paiement de Facture Mauri Pay')),
                ('paiement_marchand', models.IntegerField(default=0, verbose_name='Paiement Marchand')),
                ('paiement_salaire', models.IntegerField(default=0, verbose_name='Paiement de Salaire Mauri Pay')),
                ('rechargements_telephoniques', models.IntegerField(default=0, verbose_name='Rechargements Téléphoniques Mauri Pay')),
                ('transactions_administrations', models.IntegerField(default=0, verbose_name='Transactions avec les Administrations Publiques')),
                ('transfert_p2p', models.IntegerField(default=0, verbose_name='Transfert Personne à Personne Mauri Pay')),
                ('transfert_p2e', models.IntegerField(default=0, verbose_name='Transfert Personne à Entreprise')),
                ('retraits_cashout_cadorim', models.IntegerField(default=0, verbose_name='Retraits (Cash-out) Cadorim SA')),
                ('retraits_cashout_mauripay', models.IntegerField(default=0, verbose_name='Retraits (Cash-out) Mauri Pay')),
            ],
        ),
    ]
