# Generated by Django 4.2.1 on 2025-01-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0003_valeur_limara_valeur_mauripay_volume_limara_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeur_cadorim',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], db_index=True, max_length=20, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='valeur_limara',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], db_index=True, max_length=20, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='valeur_mauripay',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], db_index=True, max_length=20, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='volume_cadorim',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], db_index=True, max_length=20, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='volume_limara',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], db_index=True, max_length=20, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='volume_mauripay',
            name='mois',
            field=models.CharField(choices=[('Janvier', 'Janvier'), ('Février', 'Février'), ('Mars', 'Mars'), ('Avril', 'Avril'), ('Mai', 'Mai'), ('Juin', 'Juin'), ('Juillet', 'Juillet'), ('Août', 'Août'), ('Septembre', 'Septembre'), ('Octobre', 'Octobre'), ('Novembre', 'Novembre'), ('Décembre', 'Décembre')], db_index=True, max_length=20, verbose_name='Mois'),
        ),
    ]
